# ty https://gist.github.com/willprice/e07efd73fb7f13f917ea
lang: minimal
script:
  - ./dothething.sh
after_success:
  - ./.travis/push.sh
env:
  global:
    # GH_TOKEN="..."
    secure: "A/KKuPvWp2LcHShnuiTe/CcIQg1Wj7NFfT7AdM4HOftYwXBvPtUSrt2D54oPeuwM3/VUwfic8nx73Biqjt3hyP7JuUErTt3H6BfA4ayO52IXMVkCjCysbPytGw8t2m2WX/tlc2mSo25O3231ZHm54D5na3hEEoz/mqf+a62J7Mg3yL33YLWwO4NMpb/8mBW/IZ07odXMEA+zyaYG3yUwNonlVrkGzk0A6Dyxf1l/opF4p7aw7tNJ8CwRMq/tFaTwOpxtYJm2Ba0VDtzflNDUTEnL5VlQaK6U91/tYC5HDliaRHqdETyvVr3liNKhPgYYpX6xmjNYDdbdJsJf6lUYFzi5MUkhxeRweE0H9qSy8FFKmOCy8cvBr1WCrGbrFkdI2f7v2wJedbeCo6KMzad4bTEsUtLjlDPysjEg9CF3n1sXwdTm0Hmw37CfcQ4nCevHkRE/HXUqIrTbf/UBKAp+WEpeM2yoDHE+ej6pr/jdz+MNHbVTwRhrq7u08ClCPGcSoxturZlfEBeSnKYGEpWB+Xknf4NifiBUL2fhhEVAf1xKyRgLj/W1LfoX3HBRxXZXrysXztVfeaei81xBu3+WOeCjb3tJXGV43846IbzHbCIRb/uwYUIE1DpQUezg7u/Ue312nSSyEWu3o2XU1z+ccrut+JNZpNnCmS2Gu8FASmk="
